artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_url: https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv
  local_data_file: artifacts/data_ingestion/titanic.csv
  unzip_dir: ""

data_validation:
  root_dir: artifacts/data_validation
  unzip_data_dir: artifacts/data_ingestion/titanic.csv
  STATUS_FILE: artifacts/data_validation/status.txt

data_transformation:
  root_dir: artifacts/data_transformation
  transformed_train_dir: artifacts/data_transformation/train
  transformed_test_dir: artifacts/data_transformation/test

model_trainer:
  root_dir: artifacts/model_trainer
  model_file: artifacts/model_trainer/titanic_model.pkl

model_evaluation:
  root_dir: artifacts/model_evaluation
  test_data_path: artifacts/data_transformation/test.csv
  model_path: artifacts/model_trainer/titanic_model.pkl
  metric_file_name: artifacts/model_evaluation/metrics.json



